### ISSUE TITLE
Firefox: Only first word of Video in File Name and no filetype

### ISSUE THREAD

**Issue by SB97** [bennymeier/yt-downloader#2] opened 2020-02-20 22:48 UTC
When downloading a Video in Firefox the Filename is just the first word of the Videotitle:

example:
[Queen – Bohemian Rhapsody (Official Video Remastered)](https://www.youtube.com/watch?v=fJ9rUzIMcZQ)

gives you a File called "Queen" without a filetype.

**Comment by bennymeier** [comment] 2020-03-15 13:54
Thanks for your issue! I'll try to fix.

**Comment by bennymeier** [comment] 2020-03-15 16:27
The issue is fixed in the updated version.

**Closed as completed by bennymeier** 2020-03-15 16:27 UTC
Labels: bug
